name: Documentation request
description: Request changes or additions to documentation
title: "[DOC] "
labels: [documentation]
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting improvements to our documentation!

  - type: input
    id: doc_section
    attributes:
      label: Documentation Section
      description: Specify the section of the documentation that needs improvement.
      placeholder: Section name...

  - type: textarea
    id: current_state
    attributes:
      label: Current State
      description: Describe the current state of the documentation.
      placeholder: Describe the current state...

  - type: textarea
    id: improvement_suggestion
    attributes:
      label: Improvement Suggestion
      description: Describe the improvements or additions you suggest.
      placeholder: Suggest improvements...

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots related to the documentation request here.
      placeholder: Provide additional context...
