name: Feature request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: [enhancement]
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: input
    id: feature_description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you are requesting.
      placeholder: Describe the feature...

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe the use case or problem this feature would address.
      placeholder: Explain the use case...

  - type: input
    id: potential_solution
    attributes:
      label: Potential Solution
      description: Describe any solutions you've considered.
      placeholder: Describe potential solutions...

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Provide additional context...
